name: Linux CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - "releases/**"

env:
  PYTHON_VERSION: "3.11"

jobs:
  build_and_test:
    name: Build and Test (Ubuntu)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ninja-build

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools
          pip install --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly openvino==2025.3.0.dev20250710

      - name: Configure CMake
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DENABLE_PYTHON=ON \
            -GNinja

      - name: Build
        run: |
          cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Install
        run: |
          cmake --install build --config ${{ matrix.build_type }} --prefix install
      - name: Test basic functionality
        run: |
          source ${{ env.OV_INSTALL_DIR }}/setupvars.sh
          python3 -m pytest -v ${{ env.SRC_DIR }}/tests/python_tests/test_llm_pipeline.py -k "not test_perf_metrics_with_structured_output"
